"""Initial migration

Revision ID: aff1a3a846a2
Revises: 
Create Date: 2021-03-25 22:05:46.850261

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff1a3a846a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storm',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('max_wind_speed', sa.Integer(), nullable=False),
    sa.Column('min_pressure', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storm_segment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('storm_id', sa.String(length=256), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('ss_scale', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['storm_id'], ['storm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_storm_segment_geom', 'storm_segment', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('storm_point',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('storm_id', sa.String(length=256), nullable=False),
    sa.Column('storm_segment_id', sa.Integer(), nullable=False),
    sa.Column('wind_speed', sa.Integer(), nullable=False),
    sa.Column('min_pressure', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.ForeignKeyConstraint(['storm_id'], ['storm.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storm_segment_id'], ['storm_segment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_storm_point_geom', 'storm_point', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_storm_point_geom', table_name='storm_point')
    op.drop_table('storm_point')
    op.drop_index('idx_storm_segment_geom', table_name='storm_segment')
    op.drop_table('storm_segment')
    op.drop_table('storm')
    # ### end Alembic commands ###
